name: Workflow for first react poc

on:
  push:
    branches:
      - main

jobs:
  tests-unitaires:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Dependencies
        run: npm ci
      - name: Run unit tests
        run: |
          export REACT_APP_API_KEY=${{ secrets.REACT_APP_API_KEY }}
          npm run test

  deploy:
    needs: tests-unitaires
    # Le job "deploy" a besoin de l'exécution complète du job "test" pour commencer
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      # L'étape "Checkout" n'est pas nécessaire car on n'a pas besoin de cloner le repo une deuxième fois
      # Si le repo n'a pas été modifié, on récupère simplement la version qui a été construite pendant les tests end-to-end
      - name: Install Dependencies and build
        run: |
          npm ci
          export REACT_APP_API_KEY=${{ secrets.REACT_APP_API_KEY }}

          npm run build
      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: build
          token: ${{ secrets.GITHUB_TOKEN }}
  lighthouse:
    needs: deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Audit URLs using Lighthouse
        uses: treosh/lighthouse-ci-action@v9
        with:
          urls: |
            ${{ vars.REACT_APP_URL }}
          uploadArtifacts: true # enregistrer les résultats en tant qu'artefacts d'action
